### ISSUE TITLE
Jenkins 1.6x doesn't appear to be supported

### ISSUE THREAD

**Issue by skweeker** [AnyStatus/AnyStatus#70]
We still have some Jenkins 1.6 instances we'd like to monitor in AnyStatus 3.0 (they work fine in 2.9.9). When I configure a Jenkins 1.6 endpoint in AnyStatus 3.0, the job list is not populated when I go to select a job for that endpoint. Other Jenkins 2+ endpoints work fine, but not our 1.6 instances. I receive an error in the activity panel:
``
An error response received from Jenkins server.
System.Exception: An error response received from Jenkins server.
  at AnyStatus.Plugins.Jenkins.API.JenkinsApi.ExecuteAsync[T](IRestRequest request, CancellationToken cancellationToken)
  at AnyStatus.Plugins.Jenkins.Jobs.JenkinsJobHealthCheck.Handle(StatusRequest`1 request, CancellationToken cancellationToken)
  at MediatR.AsyncRequestHandler`1.MediatR.IRequestHandler<TRequest,MediatR.Unit>.Handle(TRequest request, CancellationToken cancellationToken)
  at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
  at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
  at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
  at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
  at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
``

The JSON structure looks to be different between Jenkins 1 and Jenkins 2. Jenkins 2 response may look something like this:
``
{
    "_class": "hudson.model.FreeStyleProject",
    "name": "A Real Job Type Job",
    "url": http://jenkins.server.local/job/ARealJobTypeJob/”,
    "color": "disabled"
}
``
But a Jenkins 1 response looks like this:
``
{
    "name": "A Real Job Type Job",
    "url": http://jenkins.server.local/job/ARealJobTypeJob/”,
    "color": "disabled"
}
``

**Comment by AlonAm** [comment]
Can you please provide an example to how the jobs are organized/structured on your jenkins server? Do you use folders or views?

A json request/response examples of getting the list of jobs from your server would be very helpful

**Comment by skweeker** [comment]
Hi Alon! The server does have views, however my team doesn't often use them, we just find our stuff from the job list, or via search.

So I did a GET http://builder.domain.com/api/json/jobs.

Here's the output I get back (sanitized, change server URL and job names, but you get the idea):
``
{
    "assignedLabels": [
        {}
    ],
    "mode": "NORMAL",
    "nodeDescription": "the master Jenkins node",
    "nodeName": "",
    "numExecutors": 1,
    "description": "<b>Builds for Bob</b>",
    "jobs": [
        {
            "name": "CI-Build",
            "url": "http://builder.domain.com/job/CI-Build/",
            "color": "blue"
        },
        {
            "name": "CS-Build",
            "url": "http://builder.domain.com/job/CS-Build/",
            "color": "blue"
        },
        {
            "name": "DSM-Build",
            "url": "http://builder.domain.com/job/DSM-Build/",
            "color": "blue"
        }
    ],
    "overallLoad": {},
    "primaryView": {
        "name": "All",
        "url": "http://builder.domain.com/"
    },
    "quietingDown": false,
    "slaveAgentPort": 0,
    "unlabeledLoad": {},
    "useCrumbs": true,
    "useSecurity": true,
    "views": [
        {
            "name": "All",
            "url": "http://builder.domain.com/"
        },
        {
            "name": "All Disabled",
            "url": "http://builder.domain.com/view/All%20Disabled/"
        },
        {
            "name": "All Failed",
            "url": "http://builder.domain.com/view/All%20Failed/"
        },
        {
            "name": "Utility",
            "url": "http://builder.domain.com/view/Utility/"
        }
    ]
}
``
